KAFKA_BOOTSTRAP_SERVERS = "localhost:9092"
KAFKA_TOPIC_INPUT = "videoclips"
KAFKA_TOPIC_OUTPUT = "klv.metadata.extracted"
KAFKA_GROUP_ID = "klv-metadata-consumer"

MINIO_ENDPOINT = "localhost:9000"
MINIO_ACCESS_KEY = "minioadmin"
MINIO_SECRET_KEY = "minioadmin123"
MINIO_SECURE = False

RAW_BUCKET = "raw-streaming-video"
OUTPUT_BUCKET = "klv-metadata"
OUTPUT_BUCKET_DETECTION="object-detection"

CONFIDENCE_THRESHOLD = 0.4
DISTANCE_THRESHOLD= 30
HIT_COUNTER_MAX= 30
INITIALIZATION_DELAY= 3
DISTANCE_FUNCTION= "euclidean"