KAFKA_BOOTSTRAP_SERVERS = "localhost:9092"
KAFKA_TOPIC_INPUT = "Video-segments"
KAFKA_TOPIC_OUTPUT = "pipeline-results"
KAFKA_GROUP_ID = "evISR-consumer"

MINIO_ENDPOINT = "localhost:9000"
MINIO_ACCESS_KEY = "minioadmin"
MINIO_SECRET_KEY = "minioadmin123"
MINIO_SECURE = False

RAW_BUCKET = "raw-streaming-video"
OUTPUT_BUCKET = "klv-metadata"
OUTPUT_BUCKET_DETECTION="object-detection"
OUTPUT_BUCKET_FUSION="fusion-context"
OUTPUT_PATH= "output"
OUTPUT_BUCKET_SUMMARY="llm-summaries"

CONFIDENCE_THRESHOLD = 0.5
DISTANCE_THRESHOLD= 30
HIT_COUNTER_MAX= 30
INITIALIZATION_DELAY= 3
DISTANCE_FUNCTION= "euclidean"